### ISSUE TITLE
Add support for unbounded intervals

### ISSUE THREAD

**Issue by nicoleepp** [invenia/Intervals.jl#89]
https://www.postgresql.org/docs/9.3/rangetypes.html#RANGETYPES-INFINITE

**Comment by omus** [comment]
Originally the plan was to use `nothing` to represent an interval that was unbounded. However, when implementing this design we ran into troubles when implementing `span` (the distance between the endpoints) for an unbounded interval. In this particular case it make the most sense to return some kind of infinity value. The current approach is to try and integrate Infinity.jl and see if we can add an infinity value for `TimeType`s.

**Comment by omus** [comment]
Some rules around unbounded intervals that were though of during an initial design:

- For unbounded intervals `span` should return infinity
- If the lower bound of a interval is unbounded then all points less than the upper bound are included in the interval
- If the upper bound of an interval is unbounded then all points greater than the lower bound are included in the interval
- When considering unbounded range's inclusiveness we should consider if infinity should be considered contained within the interval. e.g. `∞ in [0,∞) == false` as infinity is not actually included in this interval. More specifically all positive finite values are included in the interval but infinity is not.
- An `AnchoredInterval` uses one point and a span to calculate the other endpoint. Conversion from an `Interval` that uses one finite endpoint and another non-finite endpoint is impossible if the non-finite endpoint is the one used for the `AnchoredInterval`. This is because it would be impossible to calculate the other endpoint from the single non-finite endpoint.

**Comment by iamed2** [comment]
IMO the result of `span` on `[x,)`, `[x,∞)` and `[x,∞]` should all be the same. I think the error on unbounded intervals is a reasonable choice for now if we don't have a good way to implement that.
